# Source system specific options
if [[ -d ${HOME}/.zprofile.d ]]; then
    for file (${HOME}/.zprofile.d/**/*.zsh(N.)) . $file
fi

# dont remember commands that start with space
setopt HIST_IGNORE_SPACE

# Setup pyenv
if which pyenv 1> /dev/null 2>&1; then
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
fi
