filetype plugin indent on
syntax on

set nocompatible
set autoindent
set number
set relativenumber
set backspace=indent,eol,start
set ts=2
set sw=2

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType yml setlocal ts=2 sts=2 sw=2 expandtab

:command Nonum set nonumber norelativenumber
:command Num set number relativenumber
